---
title: "Schedule"
---

## Week 01

### Wed, Jan 14, 2026

**NO MEETING**

## Week 02

### Wed, Jan 21, 2026

- Introductions
- Lab overview
- Homework
- [Link to mtg minutes](https://gilmore-lab.github.io/lab-meetings.html)

## Week 03

### Wed, Jan 28, 2026

- Read & discuss @D-Antonio2026-vo.
- [Notes](2026-01-28-dantonio-etal.qmd)

## Week 04

### Wed, Feb 04, 2026

- Watch @EIFL2018-lx

## Week 05

### Wed, Feb 11, 2026

- Finish watching @EIFL2018-lx

## Week 06

### Wed, Feb 18, 2026

- Read & discuss @McIntire2026-fk
  - Resources
    - Adolescent Brain Cognitive Development (ABCD) [study](https://abcdstudy.org).
    - [Belmont Report](https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/index.html).

## Week 07

### Wed, Feb 25, 2026

::: {.callout-warning}
## Cancelled
We did not meet this week.
:::

## Week 08

### Wed, Mar 04, 2026

- Read & discuss @Hadad2015-qd
  - See [companion](2026-03-04-hadad-etal.qmd) Quarto document

## Week 09

### Wed, Mar 11, 2026

**NO MEETING** Spring Break

## Week 10

### Wed, Mar 18, 2026

- Continue discussion of @Hadad2015-qd
  - Deeper dive about gratings and [Gabor patches](2026-03-04-hadad-etal.qmd)

## Week 11

### Wed, Mar 25, 2026

- PLAY coding check-in
- Poster check-in
- Read and discuss @Blumberg2023-fs and possibly @Blumberg2023-ce

## Week 12

### Wed, Apr 01, 2026

## Week 13

### Wed, Apr 08, 2026

## Week 14

### Wed, Apr 15, 2026

- Watch and discuss @Veritasium2023-vk video.

## Week 15

### Wed, Apr 22, 2026

## Week 16

### Wed, Apr 29, 2026

## References

