---
title: "PSYCH 494"
subtitle: "Gilmore Lab • Spring 2026"
---

## Instructor {-}

Rick O. Gilmore, Ph.D. \
Professor of Psychology \
rog1 AT-SIGN psu PERIOD edu \

Schedule an appointment: <https://doodle.com/mm/rickgilmore/book-a-time></br>

Lab web site: <https://gilmore-lab.github.io>

## Lab Manager {-}

Andrea Seisler \

## Meeting time & location {-}

Wednesday, 4:00p - 4:50p \
Room 444 Moore Building

## Expectations

- Attend and participate in all meetings as this is a part of your grade
- Attendance expectations are the same for those who participate in lab for Credit or as a Volunteer.
- If a meeting will be missed, notify the lab manager PRIOR to missing the meeting by Discord or email or you will be marked as a no show 
- Check out the meeting minutes on the [Lab Website](https://gilmore-lab.github.io/lab-meetings.html) to see what was missed.
- Come prepared for the meeting by completing any homework assignments.

## Required Training

- [CITI Training](https://citi.psu.edu/) - every 3 years
- [Learning Resource Network](https://lrn.psu.edu/) - yearly
   - [Clery Act Training](https://gilmore-lab.github.io/protocols/training.html#clery-act-training) 
  - [Reporting Suspected Child Abuse](https://gilmore-lab.github.io/protocols/training.html#reporting-suspected-child-abuse)
  - [Values, Ethics, & Compliance Training](https://gilmore-lab.github.io/protocols/training.html#values-ethics-and-compliance-training) 
  - [Title IX Training](https://gilmore-lab.github.io/protocols/training.html#understanding-title-ix-at-penn-state) 
  - [Data Privacy at Penn State](https://gilmore-lab.github.io/protocols/training.html#data-privacy-at-penn-state)
- Background Check (only if collecting data on minors)

<!-- ## References -->

