---
title: "Schedule"
---

## Week 01

### Thu, Aug 28, 2025

0. Attending
1. Introductions
2. Fall 2025 Lab Projects (Rick)
  - Play & Learning Across a Year (PLAY) Project, [PLAY site](https://play-project.org), [Parent site](https://anhourinthelife.org), [KoBoToolbox Surveys](https://PLAY-behaviorome.github.io/KoBoToolbox/)
    - Data Collection Complete April 2025
    - Locomotion Coding in Datavyu - Fall 2025
      - 2-3 hours per video
      - 75 video committment total
  - Update [Databrary User Guide](https://databrary.github.io/guide/) to Databrary 2.0 using R Studio
  - [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/) Project
    - [Visual Acuity Analysis Procedure](https://docs.google.com/document/d/1jdoIzE1cLHphA9y89jyhK20lTXJ2WCu4fBIATH25EeY/edit?tab=t.0)
    - [Legacy Project Acuity Data: By Paper](https://docs.google.com/spreadsheets/d/1UFZkbh9oU4JHpYsrkDQcNmDyqD4J-qB74dhyMzIkqKs/edit?gid=432255138#gid=432255138)
    - [Legacy Project Data Analysis](https://docs.google.com/spreadsheets/d/1XnGweqEAiTlU8mhvWqtCCMNm9l5txdR0YpQsuMxvgio/edit?gid=998401983#gid=998401983)
  - [Databrary](https://databrary.org), especially the [Databrary Guide](https://databrary.github.io/guide), the [*databraryr* package](https://databrary.github.io/databraryr), and the [Databrary Analytics](https://databrary.github.io/analytics).
  - Refreshing internal resources, especially the [lab website](https://gilmore-lab.github.io) and our lab [protocols site](https://gilmore-lab.github.io/protocols).
  - [Datacamp](https://www.datacamp.com/) 

3. Homework
  - [Create Discord Account](https://gilmore-lab.github.io/protocols/onboarding.html#discord)
  - [CITI Training](https://gilmore-lab.github.io/protocols/training.html#citi-training) ASAP - new lab members

## Week 02

### Thu, Sep 04, 2025

## Week 03

### Thu, Sep 11, 2025

## Week 04

### Thu, Sep 18, 2025

## Week 05

### Thu, Sep 25, 2025

## Week 06

### Thu, Oct 02, 2025

**NO MEETING**

## Week 07

### Thu, Oct 09, 2025

## Week 08

### Thu, Oct 16, 2025

## Week 09

### Thu, Oct 23, 2025

## Week 10

### Thu, Oct 30, 2025

## Week 11

### Thu, Nov 06, 2025

## Week 12

### Thu, Nov 13, 2025

## Week 13

### Thu, Nov 20, 2025

## Thanksgiving

## Week 14

### Thu, Dec 02, 2025

## Week 15

### Thu, Dec 09, 2025

## References

